### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by priestjim** [priestjim/gen_rpc#1]
Enable SSL support on the receiver side and provide application configuration options to allow fine-grained security.

Attention must be paid to:
- Connection handling and failures (timeouts, connection drops) with respect to the underlying SSL implementation
- Efficiency of operation

**Comment by ostinelli** [comment]
+1

**Comment by priestjim** [comment]
Yes! Check the `refactor` branch, I'm almost done implementing the SSL driver

**Comment by ostinelli** [comment]
Oh nice! Will wait until it gets merged in then :)

**Comment by benoitc** [comment]
what does it miss as of today? do you need any help?

**Comment by priestjim** [comment]
@benoitc not much, life caught up, I'm finishing up the SSL implementation today. I wanted to implement #62 before releasing a new major version but I'll just release SSL + the refactor as 1.5 and then 2.0 with #62 implemented. Thanks for offering :)

**Comment by benoitc** [comment]
@priestjim thanks!
