### ISSUE TITLE
(Question) about commit 822f8. 

### ISSUE THREAD

**Issue by linearregression** [priestjim/gen_rpc#21]
For commit
https://github.com/priestjim/gen_rpc/commit/822f844896934a4b898b98d1dd0b1fed136ed50d
did you mean to remove just the catch or the entire socket close?

**Comment by priestjim** [comment]
gen_tcp closes the socket when the owning process dies. There's no reason to close the socket explicitly!

**Comment by linearregression** [comment]
cool. 
How about putting your presentation slides here or iin github
or a link in Readme?
