### ISSUE TITLE
[Info]ssh support

### ISSUE THREAD

**Issue by linearregression** [priestjim/gen_rpc#24]
There is a very old repo that tried to add ssh support 
https://github.com/jj1bdx/sshrpc
So far I am unable to make that repo work on a demo level. I suspect the issue may be some configuration of keys and stuff on my end. But at least the author make that good enough for presentatio at one point. (see the docs in the repo). May be a good place to investigate?

**Comment by priestjim** [comment]
I don't think that feature is in the scope of the project so I'm gonna drop it.

**Comment by linearregression** [comment]
May be an "example"? Ejabberd, Rabbitmq, Riak they all got TLS/SSL for node-node communication protection for enterprise customers. Ejabberd wrote their own tls port driver, open sourced.

The issue is full mesh epmd stuff. 
Btw, someone has ported epmd from C to Erlang in Germany fir use in assembly line 
http://www.erlang-factory.com/static/upload/media/14343429944374euctalk2015key.pdf

**Comment by priestjim** [comment]
But SSH is out of scope here. There's a task for implementing gen_rpc over SSL and do common name verification too but my branch is half-done. So SSL would be more appropriate here. And it's straightforward-ish too: just replace gen_tpc:listen with ssl:listen!
