### ISSUE TITLE
Fix travis dialyzer?

### ISSUE THREAD

**Issue by linearregression** [priestjim/gen_rpc#39]
It fails with out of memory error, does so even locally. 
Since erlang elixir not well supported in travisci,
may need to build yourself and store it in dropbox or the like to download from
http://blog.danielberkompas.com/elixir/2015/04/08/generate-dialyzer-plts-on-travis.html

**Comment by priestjim** [comment]
I researched on the matter a bit, looks like I overused most of dialyzer options for no reason. The culprit that makes dialyzer explode is -Wrace_conditions (read more here http://erlang.org/doc/man/dialyzer.html). I also removed a bunch of warning kill switches, because, apparently, we need them!
