### ISSUE TITLE
node naming and addresses

### ISSUE THREAD

**Issue by benoitc** [priestjim/gen_rpc#57]
How does gen_rpc knows where a node is? Does it still use epmd for it?

**Comment by benoitc** [comment]
never-mind found my answer. So the host is given via the node name 'name@host' and the port is provided via a known port in the application environment. Either specific for the host or global.

Closing the issue then but maybe you could document it?

**Comment by priestjim** [comment]
Before version 1.0, it used to connect to the remote node using rpc:call, which used distributed Erlang. Wanting to make gen_rpc truly distributed, I moved from rpc:call to a TCP listener and extracting the remote node from the right side of the @ sign (hence it only supports long names). I will be documenting it together with the multiple-connections-per-node feature.
