### ISSUE TITLE
try ... cacth never handle erlang:kill

### ISSUE THREAD

**Issue by NOMORECOFFEE** [priestjim/gen_rpc#58]
For example `gen_rpc:call(<not_local_node>, timer, kill_after, [0])`

**Comment by priestjim** [comment]
I'm ok with that, that's not being handled by rpc:call either!

**Comment by NOMORECOFFEE** [comment]
It isn't right. `rpc:call` return `{badrpc,{'EXIT',killed}}`

**Comment by NOMORECOFFEE** [comment]
gen_rpc should use like in rpc https://github.com/erlang/otp/blob/maint/lib/kernel/src/rpc.erl#L200 or use middleman process https://github.com/erlang/otp/blob/maint/lib/kernel/src/rpc.erl#L338

**Comment by priestjim** [comment]
This requires some pretty steep changes to deal with, including keeping track of workers, which creates garbage in the acceptor state and extra messages. Do you believe it's worth it?

**Comment by NOMORECOFFEE** [comment]
Hi. If we don't  set `call_receive_timeout` into `infintity`, then everything will be fine.

**Comment by NOMORECOFFEE** [comment]
Or we can use another middleman process [here](https://github.com/priestjim/gen_rpc/blob/master/src/gen_rpc_acceptor.erl#L203) and don't touch  the acceptor state.

**Comment by NOMORECOFFEE** [comment]
@priestjim I wanted to warn only about spawn_link/kill. They will be able to block caller process to infinit time.

**Comment by priestjim** [comment]
This is a real issue but affects very few of real world cases (making RPC calls on functions that use messages and self() such as timer:kill_after). I am thinking about making a special "call" case with receive timeout infinity and handle it with a middleman process or with trapping exits but that will render reply inconsistencies (call with infinity will return killed, call with timeout will return timeout)
