### ISSUE TITLE
Question: tcp_server_port vs tcp_client_port

### ISSUE THREAD

**Issue by lrascao** [priestjim/gen_rpc#68]
I'm trying out `gen_rpc`, i launch two nodes in the same machine (`node1` with `{tcp_server_port, 7331}` and `node2` with `{tcp_server_port, 7332}`). 
When i try a `gen_rpc:call('node2@127.0.0.1', 'erlang', 'node', []).` it fails because `{badrpc,econnrefused}` trying to connect to the default port `5369` on `node2`. If i set `application:set_env(gen_rpc, tcp_client_port, 7332).`  on `node1` it succeeds, shouldn't there be a way of `node1` automatically discovering on what port `node2` is listening on?

**Comment by priestjim** [comment]
gen_rpc supports external port discovery by way of supporting a `Module:get_config(Node)` call that can bind to external service discovery services. To use it you have to:

- Set `{gen_rpc, client_config_per_node}` to `{external, Module}`
- Build a `Module:get_config(Node)` module and function that consults your external service discovery and returns the `{Driver, Port}` gen_rpc needs to connect to that node

Please note that by doing this, you also have to manually code the Driver/Port registration part that actually registers each node's Driver/Port pair to the external service discovery service

**Comment by lrascao** [comment]
thanks for the tip, in your opinion is it feasible to implement this based on epmd?

**Comment by pj-splunk** [comment]
You can implement a pseudo-epmd system that reads the gen_rpc environment and extracts ports per node locally and communicates with other pseudo-epmd apps on remote nodes over a standard port but that looks like more work than just using etcd or consul to register/deregister your port and then use the {external, Module} system that gen_rpc offers.

**Comment by lrascao** [comment]
i was thinking of actually registering and consulting ports directly in epmd using the `{external, Module}`, i know for sure that will be available where an erlang node is running

**Comment by pj-splunk** [comment]
That could work but it might confuse actual distributed Erlang nodes running in the same cluster! If you do it, let me know how it goes (and possibly make a PR :))

**Comment by lrascao** [comment]
`erl_epmd` doesn't allow me to register any other node/port pair once it's registered, i ended implementing an external module that simply makes a rpc call to the remote node in order to obtain it's `tcp_server_port` config var, thanks for the help!
