### ISSUE TITLE
[Question] Why is it called Out-of-band messaging?

### ISSUE THREAD

**Issue by linearregression** [priestjim/gen_rpc#7]
It looks like the library is for 'virtual Erlang node'.
At a glance:
- spawn Erlang node if absent (if resource available(?)), 
     * talk to one if present and do a sync & async rpc (sync)
     * 'relay' message along with new addressee and/or sender

Out of band is usually communication outside the logical data stream. E.g. signalling in telecom switch is done via a signalling plane ant not sharing logical resource with the data stream ). 

Just wondering.

**Comment by priestjim** [comment]
It is out of band because it's not using the usual Erlang VM's channels for communication (the VM's remote spawn mechanism or rpc/rex)!

**Comment by linearregression** [comment]
Thanks. 
Oh you are referring to rpc and rex server. 
I was thinking about something else.
