### ISSUE TITLE
rebar.config {hut, "~> 1.2"} fails

### ISSUE THREAD

**Issue by etsangsplk** [priestjim/gen_rpc#73]
===> 20.0 satisfies the requirement for minimum OTP version 19.1
===> Package <<"hut">> not found. Fetching registry updates and trying again...
===> Updating package registry... 
Changing rebar.config
From:
{hut, "~> 1.2"},
https://hex.pm/packages/hut
to 
    {hut, "1.2.0"},
Solved the issue

**Comment by priestjim** [comment]
Cannot reproduce!

**Comment by etsangsplk** [comment]
It turned out to be an error with old version of rebar3 on OTP 20
rebar 3.0.0-beta.4+build.165.ref7fab47d on Erlang/OTP 20 Erts 9.0
upgraded to 
rebar 3.4.2 on Erlang/OTP 20 Erts 9.0
it is ok
