### ISSUE TITLE
some question about gen_rpc:call

### ISSUE THREAD

**Issue by snailman** [priestjim/gen_rpc#75]
First, thanks for this repo. 

is it working when local node call gen_rpc:call？
1. the remote node return big binary(eg,50MB)
2. the network is buy,the return data from remote node can not be received at once

thx u.

**Comment by priestjim** [comment]
Yes, you can adjust the send and receive timeouts in the application's settings to allow for delays in message delivery. If you expect network congestion, I'd recommend adjusting both network timeouts and `call` timeouts.

**Comment by snailman** [comment]
i got it ,thx
